syntax = "proto3";

option csharp_namespace = "Eladei.BookRating.Api";
package book.v1;

import "google/protobuf/timestamp.proto";

service BookRating {
	rpc RegisterBook (RegisterBookApiRequest) returns (RegisterBookApiResponse);

	rpc RemoveBook (RemoveBookApiRequest) returns (RemoveBookApiResponse);

	rpc UpdateBook(UpdateBookApiRequest) returns (UpdateBookApiResponse);

	rpc VoteForBook(VoteForBookApiRequest) returns (VoteForBookApiResponse);

	rpc GetBooks (GetBooksApiRequest) returns (GetBooksApiResponse);
}

message RegisterBookApiRequest {
	string name = 1;
	string author = 2;
}

message RegisterBookApiResponse {
	string bookId = 1;
}

message RemoveBookApiRequest {
	string bookId = 1;
}

message RemoveBookApiResponse { }

message UpdateBookApiRequest {
    string bookId = 1;
	string name = 2;
	string author = 3;
}

message UpdateBookApiResponse { }

message VoteForBookApiRequest {
    string bookId = 1;
}

message VoteForBookApiResponse { }

message GetBooksApiRequest {
	uint32 booksPerPage = 1;
    uint32 page = 2;
}

message GetBooksApiResponse {
	uint32 totalPages = 1;
	repeated BookInfoApiModel allPositions = 2;
}

message BookInfoApiModel {
    string bookId = 1;
	string name = 2;
	string author = 3;
	uint32 votes = 4;
	google.protobuf.Timestamp registeredAt = 5;
}
