syntax = "proto3";

option csharp_namespace = "Eladei.BookRating.Api";
package book.v1;

import "google/protobuf/timestamp.proto";

// Service for working with book rating
service BookRating {
	// Registers a book in the rating
	rpc RegisterBook (RegisterBookApiRequest) returns (RegisterBookApiResponse);

	// Removes a book from the rating
	rpc RemoveBook (RemoveBookApiRequest) returns (RemoveBookApiResponse);

	// Updates book information in the rating
	rpc UpdateBook(UpdateBookApiRequest) returns (UpdateBookApiResponse);

	// Votes for a book in the rating
	rpc VoteForBook(VoteForBookApiRequest) returns (VoteForBookApiResponse);

	// Returns a list of books in the rating
	rpc GetBooks (GetBooksApiRequest) returns (GetBooksApiResponse);
}

// Request to add a book to the rating
message RegisterBookApiRequest {
	string name = 1;
	string author = 2;
}

// Response containing the result of the book registration operation
message RegisterBookApiResponse {
	string bookId = 1;
}

// Request to remove a book from the rating
message RemoveBookApiRequest {
	string bookId = 1;
}

// Response containing the result of the book removal operation
message RemoveBookApiResponse { }

// Request to update book information in the rating
message UpdateBookApiRequest {
    string bookId = 1;
	string name = 2;
	string author = 3;
}

// Response containing the result of the book update operation
message UpdateBookApiResponse { }

// Request to vote for a book in the rating
message VoteForBookApiRequest {
    string bookId = 1;
}

// Response containing the result of the voting operation
message VoteForBookApiResponse { }

// Request to get a list of books in the rating
message GetBooksApiRequest {
	uint32 booksPerPage = 1;
    uint32 page = 2;
}

// Response containing a list of books in the rating
message GetBooksApiResponse {
	uint32 totalPages = 1;
	repeated BookInfoApiModel allPositions = 2;
}

// Book information in the rating
message BookInfoApiModel {
    string bookId = 1;
	string name = 2;
	string author = 3;
	uint32 votes = 4;
	google.protobuf.Timestamp registeredAt = 5;
}