//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eladei.Architecture.Cqrs.Ddd.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eladei.Architecture.Cqrs.Ddd.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обработке команды &apos;{0}&apos; достигнут предел попыток обновления информации в источнике данных. Всего {1} попыток.
        /// </summary>
        public static string CommandDataSourceUpdateAttemptLimitReachedError {
            get {
                return ResourceManager.GetString("CommandDataSourceUpdateAttemptLimitReachedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение команды &apos;{0}&apos; отменено.
        /// </summary>
        public static string CommandExecutingCancelled {
            get {
                return ResourceManager.GetString("CommandExecutingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при выполнении команды &apos;{0}&apos;.
        /// </summary>
        public static string CommandExecutingError {
            get {
                return ResourceManager.GetString("CommandExecutingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение команды &apos;{0}&apos; началось.
        /// </summary>
        public static string CommandExecutingStarted {
            get {
                return ResourceManager.GetString("CommandExecutingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение команды &apos;{0}&apos; успешно завершено.
        /// </summary>
        public static string CommandExecutingSuccessfullyFinished {
            get {
                return ResourceManager.GetString("CommandExecutingSuccessfullyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обработке команды &apos;{0}&apos; достигнут предел попыток обновления информации в источнике данных. Всего {1} попыток.
        /// </summary>
        public static string CommandUpdateDataSourceAttemptLimitReachedError {
            get {
                return ResourceManager.GetString("CommandUpdateDataSourceAttemptLimitReachedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение запроса &apos;{0}&apos; отменено.
        /// </summary>
        public static string QueryExecutingCancelled {
            get {
                return ResourceManager.GetString("QueryExecutingCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при выполнении запроса &apos;{0}&apos;.
        /// </summary>
        public static string QueryExecutingError {
            get {
                return ResourceManager.GetString("QueryExecutingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение запроса &apos;{0}&apos; началось.
        /// </summary>
        public static string QueryExecutingStarted {
            get {
                return ResourceManager.GetString("QueryExecutingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение запроса &apos;{0}&apos; успешно завершено.
        /// </summary>
        public static string QueryExecutingSuccessfullyFinished {
            get {
                return ResourceManager.GetString("QueryExecutingSuccessfullyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код недостижим.
        /// </summary>
        public static string UnreachableCodeError {
            get {
                return ResourceManager.GetString("UnreachableCodeError", resourceCulture);
            }
        }
    }
}
